// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/haradayoshitsugucz/purple-server/api/presentation/controller"
	"github.com/haradayoshitsugucz/purple-server/api/presentation/middleware"
	"github.com/haradayoshitsugucz/purple-server/api/service"
	"github.com/haradayoshitsugucz/purple-server/config"
	"github.com/haradayoshitsugucz/purple-server/infra/aws"
	"github.com/haradayoshitsugucz/purple-server/infra/dao"
	"net/http"
	"time"
)

// Injectors from wire.go:

func InitHandler(conf config.Config, timeNow func() time.Time, cli *http.Client) *ControllerAndMiddleware {
	secretsManager := aws.NewSecretsManager(conf)
	secretsRepository := aws.NewSecretsRepository(secretsManager)
	dbCluster := dao.NewDBCluster(conf, secretsRepository)
	statusRepository := dao.NewStatusRepository(dbCluster)
	statusService := service.NewStatusService(statusRepository)
	statusController := controller.NewStatusController(conf, statusService)
	productRepository := dao.NewProductRepository(dbCluster)
	brandRepository := dao.NewBrandRepository(dbCluster)
	transactionRepository := dao.NewTransactionRepository(dbCluster)
	productService := service.NewProductService(productRepository, brandRepository, transactionRepository)
	productController := controller.NewProductController(productService)
	controllerController := &controller.Controller{
		StatusController:  statusController,
		ProductController: productController,
	}
	timeMiddle := middleware.NewTimeMiddle(timeNow)
	middlewareMiddleware := &middleware.Middleware{
		TimeMiddle: timeMiddle,
	}
	controllerAndMiddleware := &ControllerAndMiddleware{
		Ctrl:   controllerController,
		Middle: middlewareMiddleware,
	}
	return controllerAndMiddleware
}

// wire.go:

// repository
var repositorySet = wire.NewSet(dao.NewDBCluster, dao.NewStatusRepository, dao.NewProductRepository, dao.NewBrandRepository, dao.NewTransactionRepository, aws.NewSecretsManager, aws.NewSecretsRepository)

// service
var serviceSet = wire.NewSet(service.NewStatusService, service.NewProductService)

// controller
var controllerSet = wire.NewSet(controller.NewStatusController, controller.NewProductController)

var middlewareSet = wire.NewSet(middleware.NewTimeMiddle)
